name: Store News Articles

on: 
  workflow_dispatch:
    
env:
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  USER_AGENT: ${{ vars.USER_AGENT }}
  
jobs:
  scrape-news:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.0"

      - name: Install Conda 23.5.2
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py311_23.5.2-0-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: Create Conda Environment
        shell: bash -l {0}
        run: |
          source $HOME/miniconda/bin/activate
          conda init bash
          conda env create --file environment.yml --name Adaptive_Rag

      - name: Extract and Store News Articles
        run: |
            source $HOME/miniconda/bin/activate
            conda activate Adaptive_Rag 
            python -m scripts.news_scraper 